# Generated by Django 5.2 on 2026-02-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'начат'), ('in_progress', 'в процессе'), ('finished', 'завершен')], default='init', max_length=20),
        ),
    ]
