# Generated by Django 5.2 on 2026-02-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='started_at',
            new_name='created_at',
        ),
    ]
