# Generated by Django 5.2 on 2026-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_alter_athleteinfo_goal_alter_athleteinfo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goal',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
