# Generated by Django 5.2 on 2026-02-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_alter_athleteinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='goal',
            new_name='goals',
        ),
    ]
